# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News pod update --no-repo-update
  pod 'Alamofire' ,'4.8.1' #,'~> 4.8.1'
  pod 'SwiftyJSON' , '4.2.0'
  pod 'HandyJSON' , '4.2.1'
  pod 'Kingfisher' , '5.1.0'
  pod 'IBAnimatable', '5.2.1'
  pod 'SwiftTheme', '0.4.3'
  pod 'RxSwift','4.5.0'
  pod 'RxCocoa','4.5.0'
  pod 'SQLite.swift','0.11.4'
end
